apiVersion: v1
kind: ConfigMap

metadata:
  name: stock-config

data:
  DATABASE_URL: jdbc:mysql://db-stock.cle0goquw1w8.us-east-1.rds.amazonaws.com:3306/db-stock

  RABBITMQ_HOST: rabbit.rabbitmq-system.svc.cluster.local

  CONTEXT_CONFIG: DEBUG