apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: default
type: Opaque
stringData:
  default_user.conf: |
    default_user = user
    default_pass = super-secure-password
  username: user
  password: super-secure-password
