apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbit
  namespace: rabbitmq-system
spec:
  replicas: 1
  image: rabbitmq:4.0.3-management-alpine
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
              - name: rabbitmq
                resources:
                  requests:
                    memory: "1Gi"
                    cpu: "500m"
                  limits:
                    memory: "1.5Gi"
                    cpu: "1"

                volumeMounts:
                  - mountPath: /etc/rabbitmq/definitions.json
                    subPath: definitions.json
                    name: definitions
            volumes:
              - name: definitions
                configMap: # Configmap en k8s
                  name: definitions # Nombre del configmap
  rabbitmq:
    additionalConfig: |
      load_definitions = /etc/rabbitmq/definitions.json  # Path to the mounted definitions file
