apiVersion: v1
kind: ConfigMap

metadata:
  name: auth-config

data:
  DATABASE_URL: "postgres://postgres.jreaedjtytgyaxhqiiqz:pnq8bpJgis3AFh8i@aws-0-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require"

  DEBUG: 'True'