apiVersion: v1
kind: Secret

metadata:
  name: auth-secrets

type: Opaque

data:
  SECRET_KEY: 'MWM2c2Qydj00MzdudCFkX3gpay1zN18zaDd4bWU5QCZnMGgtJW1qdyEmc29ycHd5cXc='
  
  JWT_SECRET_KEY: 'NzhUWit1S3RvSmx2ZzlOMFBHWmlSUTMwa3Q0UUx5ZGM2QlpBYWNWN1hVRT0='