apiVersion: apps/v1
kind: Deployment

metadata:
  name: transaction-db-deployment
  labels:
    app: transaction-db

spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-db

  template:
    metadata:
      labels:
        app: transaction-db

    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "transaction"
                operator: In
                values:
                - "true"

      containers:
      - name: transaction-db

        image: mysql:5.6

        ports:
        - containerPort: 3306

        volumeMounts:
        - name: transaction-db-volume
          mountPath: /var/lib/mysql

        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: transaction-secrets
              key: DATABASE_USER
        
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: transaction-secrets
              key: DATABASE_PASSWORD

        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: transaction-secrets
              key: DATABASE_PASSWORD_ROOT
        
        - name: MYSQL_DATABASE 
          valueFrom:
            configMapKeyRef:
              name: transaction-config
              key: DATABASE_NAME
    
      volumes:
      - name: transaction-db-volume
        persistentVolumeClaim:
          claimName: transaction-db-volume

---

apiVersion: v1
kind: Service

metadata:
  name: transaction-db-service

spec:
  type: ClusterIP

  selector:
    app: transaction-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306